FROM golang:latest as build
COPY web /app
WORKDIR /app
RUN ls

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" dispatcher.go

FROM alpine:latest
COPY --from=build /app/dispatcher /app/dispatcher
COPY --from=build /app/static /app/static
WORKDIR /app
RUN ls

CMD ["sh", "-c", "./dispatcher"]

EXPOSE 80